# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOuX3yBJG1oxsAU7jYRdB4JjBkUAHNBc
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("jsphyg/weather-dataset-rattle-package")

print("Path to dataset files:", path)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

df = pd.read_csv(path + "/weatherAUS.csv")
df.head()

df.info()

df['RainToday'].fillna('No', inplace=True)
df['RainTomorrow'].fillna('No', inplace=True)

# Convert 'RainToday' and 'RainTomorrow' to numerical (0 or 1)
df['RainToday'] = df['RainToday'].map({'No': 0, 'Yes': 1})
df['RainTomorrow'] = df['RainTomorrow'].map({'No': 0, 'Yes': 1})
df['Date'] = pd.to_datetime(df['Date'])

X = df.drop('RainTomorrow', axis=1)
y = df['RainTomorrow']

X = X.drop('Date', axis=1)

# Identify remaining categorical columns for one-hot encoding
categorical_cols_to_encode = X.select_dtypes(include='object').columns
X = pd.get_dummies(X, columns=categorical_cols_to_encode, drop_first=True)

print("X after one-hot encoding:")
display(X.head())
print("\nInfo of X after one-hot encoding:")
X.info()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

"""### Building a Preprocessing Pipeline

To effectively handle missing values and scale numerical features, we can use a `Pipeline` from scikit-learn. This streamlines the preprocessing steps and ensures that transformations learned from the training data are applied identically to the test data.

We'll use:

*   **`SimpleImputer`**: To fill missing numerical values. A common strategy is to use the `mean` or `median`.
*   **`StandardScaler`**: To standardize numerical features (mean=0, variance=1). This is often beneficial for algorithms like Logistic Regression.
"""

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

preprocessor = numerical_transformer

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Shape of X_train_processed:", X_train_processed.shape)
print("Shape of X_test_processed:", X_test_processed.shape)

model_pipeline = LogisticRegression(max_iter=2000, solver='liblinear')
model_pipeline.fit(X_train_processed, y_train)

from sklearn.metrics import accuracy_score

y_pred = model_pipeline.predict(X_test_processed)
accuracy = accuracy_score(y_test, y_pred)

print(f"Model Accuracy on Test Set: {accuracy:.4f}")

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Plot the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['No Rain', 'Rain'], yticklabels=['No Rain', 'Rain'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

